steps:
  # build the container image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/${PROJECT_ID}/${_GCRUN_INSTANCE}", "."]

  # push the container image
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/${PROJECT_ID}/${_GCRUN_INSTANCE}"]

  # migrate Cloud SQL db - default
  - name: "gcr.io/google-appengine/exec-wrapper"
    args:
      [
        "-i",
        "gcr.io/${PROJECT_ID}/${_GCRUN_INSTANCE}",
        "-s",
        "${PROJECT_ID}:${_REGION}:${_POSTG_INSTANCE}",
        "--",
        "python",
        "manage.py",
        "migrate",
        "--settings=config.settings.production",
      ]

  # push static files to Cloud Bucket
  - name: "gcr.io/google-appengine/exec-wrapper"
    args: [
        "-i",
        "gcr.io/${PROJECT_ID}/${_GCRUN_INSTANCE}",
        # "-s",
        # "${PROJECT_ID}:${_REGION}:${_POSTG_INSTANCE}",
        "--",
        "python",
        "manage.py",
        "collectstatic",
        "--no-input",
        "--settings=config.settings.production",
      ]

  # deploy to Cloud Run
  # https://cloud.google.com/run/pricing
  # Beta
  # https://cloud.google.com/sdk/gcloud/reference/beta/run/deploy
  # Stable
  # https://cloud.google.com/sdk/gcloud/reference/run/deploy
  - name: "gcr.io/cloud-builders/gcloud"
    args: [
        "beta",
        "run",
        "deploy",
        "${_GCRUN_INSTANCE}",
        "--memory",
        "512Mi",
        "--image",
        "gcr.io/${PROJECT_ID}/${_GCRUN_INSTANCE}",
        "--region",
        "${_REGION}",
        "--platform",
        "managed",
        "--min-instances",
        "1",
        "--max-instances",
        "4",
        "--concurrency",
        "10",
        "--allow-unauthenticated",
        # "--add-cloudsql-instances",
        # "${PROJECT_ID}:${_REGION}:${_POSTG_INSTANCE}",
        "--set-env-vars",
        "DJANGO_SETTINGS_MODULE=config.settings.production,DJANGO_READ_DOT_ENV_FILE=True",
        "--vpc-connector",
        "mlapiconnectorvpc",
        "--set-secrets",
        "/usr/src/app/secrets/.env=${_env_settings}:latest",
      ]

timeout: 300s
