version: "3"

volumes:
  ml_api_local_postgres_data: {}
  ml_api_local_postgres_data_backups: {}

services:
  django:
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 3G
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: ml_api_local_django
    container_name: ml_api_local_django
    platform: linux/x86_64
    depends_on:
      - postgres
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: ml_api_production_postgres
    container_name: ml_api_local_postgres
    volumes:
      - ml_api_local_postgres_data:/var/lib/postgresql/data:Z
      - ml_api_local_postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.local/.postgres
    ports:
      - "5432:5432"
