# Generated by Django 3.2.15 on 2022-09-05 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelSink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('version', models.CharField(max_length=500)),
                ('url', models.URLField(max_length=1000)),
            ],
            options={
                'db_table': 'model_sink',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='modelsink',
            index=models.Index(fields=['name', 'version'], name='model_sink_name_5a5417_idx'),
        ),
        migrations.AddConstraint(
            model_name='modelsink',
            constraint=models.UniqueConstraint(fields=('name', 'version'), name='models_sink_pk'),
        ),
    ]
