# Generated by Django 3.2.15 on 2022-09-05 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0002_auto_20220905_2305'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='modelsink',
            name='models_sink_pk',
        ),
        migrations.AddConstraint(
            model_name='modelsink',
            constraint=models.UniqueConstraint(fields=('name', 'version', 'algorithm'), name='models_sink_pk'),
        ),
    ]
