# Generated by Django 3.2.15 on 2022-09-07 04:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0003_auto_20220905_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelsink',
            name='metrics',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), blank=True, default=None, null=True, size=None),
        ),
        migrations.AddField(
            model_name='modelsink',
            name='sample_input',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='modelsink',
            name='sample_output',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
