# Generated by Django 3.2.15 on 2022-09-07 05:02

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0004_auto_20220907_0420'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionsHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('input_data', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), size=None)),
                ('full_response', models.JSONField(blank=True, default=None, null=True)),
                ('response', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), size=None)),
                ('comments', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('algorithm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predictor.modelsink')),
            ],
            options={
                'db_table': 'predictions_history',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='predictionshistory',
            index=models.Index(fields=['created_at', 'algorithm'], name='predictions_created_a39b78_idx'),
        ),
    ]
